### ISSUE TITLE
Fix wins precent

### ISSUE THREAD

**Issue by daniel110** [med3590/AdvanceProgrammingProj#13]
http://moodle.tau.ac.il/mod/forum/discuss.php?d=64399
חישוב של אחוז הנצחונות הוא מספר הנצחונות חלקי מספר הנצחונות ועוד מספר ההפסדים:
% = Wins/(Wins+Losses)

==>
צריך להוסיף גם לסכום הפסדים או תיקויים

**Comment by med3590** [comment]
זה כבר ככה. זה נצחונות חלקי כל המשחקים.
אנחנו מחשיבים משחקים שהם תיקו להפסדים.

לא הבנתי את המשפט האחרון.

תחליט אם לסגור issue

**Comment by daniel110** [comment]
לפי מה שאני מבין מהתגובה:
תיקו =! הפסד

**Comment by med3590** [comment]
הבנתי. תוקן
