### ISSUE TITLE
השחקנים צריכים לדעת להתאפס

### ISSUE THREAD

**Issue by med3590** [med3590/AdvanceProgrammingProj#4]
לפי הדיון הזה:
http://moodle.tau.ac.il/mod/forum/discuss.php?d=63067

השחקנים צריכים לדעת לשחק שוב מחשב גם אם הם שיחקו כבר משחק.

**Comment by daniel110** [comment]
fixed in commit: https://github.com/med3590/AdvanceProgrammingProj/commit/d7c478ce8b888b1dde0d034be82f7101fa687790

only minor change - most of the stuff was ok
